Blog/Controllers/CadastroAutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class CadastroAutorController : Controller
    {
        // GET: CadastroAutor
        public ActionResult Index()
        {
            return View();
        }
    }
}

Blog/Controllers/PostagemController.cs
using Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class PostagemController : Controller
    {
        Model1 modelo = new Model1();
        // GET: CadastroPost
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public void CriarPostagem(POSTAGEM post)
        {
            post.ID_USUARIO_CRIADOR = (long)Session["IdUsuario"];
            post.DATA_CRIACAO = DateTime.Now;

            // Solicitar um redirecionamento para o provedor de logon externo
            modelo.POSTAGEM.Add(post);
            modelo.SaveChanges();
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult ListAll()
        {
            var lista = modelo.POSTAGEM.ToList();
            return  Json(lista,JsonRequestBehavior.AllowGet );
        }
        
    }
}

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body ng-app="blog">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li @(Session["Administrador"] == null || (bool)Session["Administrador"] == false ? "class=hidden" : "" )>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Cadastrar Autores", "CadastroAutor", "CadastroAutor")</li>
                    <li>@(Session["Administrador"] == null || (bool)Session["Administrador"] == false ? "class=hidden" : "" )>@Html.ActionLink("Cadastro de Postagem", "Index", "Postagem")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/module")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/home")
    @Scripts.Render("~/bundles/conta")
    @Scripts.Render("~/bundles/postagem")
    @RenderSection("scripts", required: false)
</body>
</html>